apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: k8s-recommendation-engine
    app.kubernetes.io/managed-by: kustomize
