apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-recommendation-engine

resources:
  - namespace.yaml
  - rbac.yaml
  - pvc.yaml
  - deployment.yaml

configMapGenerator:
  - name: k8s-recommendation-engine-profile
    files:
      - shipyard-profile.yaml=shipyard-profile.yaml

generatorOptions:
  disableNameSuffixHash: true
