apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-recommendation-engine-state
  namespace: k8s-recommendation-engine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
