//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfile) DeepCopyInto(out *ApplicationProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfile.
func (in *ApplicationProfile) DeepCopy() *ApplicationProfile {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileList) DeepCopyInto(out *ApplicationProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileList.
func (in *ApplicationProfileList) DeepCopy() *ApplicationProfileList {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileSpec) DeepCopyInto(out *ApplicationProfileSpec) {
	*out = *in
	out.Git = in.Git
	if in.SharedSignals != nil {
		in, out := &in.SharedSignals, &out.SharedSignals
		*out = make([]SharedSignal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Workloads != nil {
		in, out := &in.Workloads, &out.Workloads
		*out = make([]WorkloadSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MetricProfiles != nil {
		in, out := &in.MetricProfiles, &out.MetricProfiles
		*out = make(map[string]MetricProfile, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ReconcileInterval != nil {
		in, out := &in.ReconcileInterval, &out.ReconcileInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileSpec.
func (in *ApplicationProfileSpec) DeepCopy() *ApplicationProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileStatus) DeepCopyInto(out *ApplicationProfileStatus) {
	*out = *in
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
	if in.NextReconcileTime != nil {
		in, out := &in.NextReconcileTime, &out.NextReconcileTime
		*out = (*in).DeepCopy()
	}
	out.Summary = in.Summary
	if in.Workloads != nil {
		in, out := &in.Workloads, &out.Workloads
		*out = make([]WorkloadStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Proposal != nil {
		in, out := &in.Proposal, &out.Proposal
		*out = new(ProposalStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileStatus.
func (in *ApplicationProfileStatus) DeepCopy() *ApplicationProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileSummary) DeepCopyInto(out *ApplicationProfileSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileSummary.
func (in *ApplicationProfileSummary) DeepCopy() *ApplicationProfileSummary {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityRecoveryPolicySpec) DeepCopyInto(out *AvailabilityRecoveryPolicySpec) {
	*out = *in
	if in.FailureGracePeriod != nil {
		in, out := &in.FailureGracePeriod, &out.FailureGracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Cooldown != nil {
		in, out := &in.Cooldown, &out.Cooldown
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityRecoveryPolicySpec.
func (in *AvailabilityRecoveryPolicySpec) DeepCopy() *AvailabilityRecoveryPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AvailabilityRecoveryPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundsSpec) DeepCopyInto(out *BoundsSpec) {
	*out = *in
	out.Replicas = in.Replicas
	out.CPU = in.CPU
	out.Memory = in.Memory
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundsSpec.
func (in *BoundsSpec) DeepCopy() *BoundsSpec {
	if in == nil {
		return nil
	}
	out := new(BoundsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeBounds) DeepCopyInto(out *ChangeBounds) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeBounds.
func (in *ChangeBounds) DeepCopy() *ChangeBounds {
	if in == nil {
		return nil
	}
	out := new(ChangeBounds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidencePolicySpec) DeepCopyInto(out *ConfidencePolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidencePolicySpec.
func (in *ConfidencePolicySpec) DeepCopy() *ConfidencePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ConfidencePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitSpec) DeepCopyInto(out *GitSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitSpec.
func (in *GitSpec) DeepCopy() *GitSpec {
	if in == nil {
		return nil
	}
	out := new(GitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitStatus) DeepCopyInto(out *GitStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitStatus.
func (in *GitStatus) DeepCopy() *GitStatus {
	if in == nil {
		return nil
	}
	out := new(GitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmValuePaths) DeepCopyInto(out *HelmValuePaths) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CPURequest != nil {
		in, out := &in.CPURequest, &out.CPURequest
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MemoryRequest != nil {
		in, out := &in.MemoryRequest, &out.MemoryRequest
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmValuePaths.
func (in *HelmValuePaths) DeepCopy() *HelmValuePaths {
	if in == nil {
		return nil
	}
	out := new(HelmValuePaths)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmValuesSpec) DeepCopyInto(out *HelmValuesSpec) {
	*out = *in
	in.Paths.DeepCopyInto(&out.Paths)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmValuesSpec.
func (in *HelmValuesSpec) DeepCopy() *HelmValuesSpec {
	if in == nil {
		return nil
	}
	out := new(HelmValuesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricProfile) DeepCopyInto(out *MetricProfile) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make(map[string]Signal, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricProfile.
func (in *MetricProfile) DeepCopy() *MetricProfile {
	if in == nil {
		return nil
	}
	out := new(MetricProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySpec) DeepCopyInto(out *PolicySpec) {
	*out = *in
	in.Safety.DeepCopyInto(&out.Safety)
	out.Confidence = in.Confidence
	in.AvailabilityRecovery.DeepCopyInto(&out.AvailabilityRecovery)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySpec.
func (in *PolicySpec) DeepCopy() *PolicySpec {
	if in == nil {
		return nil
	}
	out := new(PolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposalStatus) DeepCopyInto(out *ProposalStatus) {
	*out = *in
	if in.BlockReasons != nil {
		in, out := &in.BlockReasons, &out.BlockReasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposalStatus.
func (in *ProposalStatus) DeepCopy() *ProposalStatus {
	if in == nil {
		return nil
	}
	out := new(ProposalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryStatus) DeepCopyInto(out *RecoveryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryStatus.
func (in *RecoveryStatus) DeepCopy() *RecoveryStatus {
	if in == nil {
		return nil
	}
	out := new(RecoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaBounds) DeepCopyInto(out *ReplicaBounds) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaBounds.
func (in *ReplicaBounds) DeepCopy() *ReplicaBounds {
	if in == nil {
		return nil
	}
	out := new(ReplicaBounds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetyPolicySpec) DeepCopyInto(out *SafetyPolicySpec) {
	*out = *in
	if in.AllowAutoCommit != nil {
		in, out := &in.AllowAutoCommit, &out.AllowAutoCommit
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UrgentBypassAllowed != nil {
		in, out := &in.UrgentBypassAllowed, &out.UrgentBypassAllowed
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetyPolicySpec.
func (in *SafetyPolicySpec) DeepCopy() *SafetyPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SafetyPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingSpec) DeepCopyInto(out *ScalingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingSpec.
func (in *ScalingSpec) DeepCopy() *ScalingSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedSignal) DeepCopyInto(out *SharedSignal) {
	*out = *in
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedSignal.
func (in *SharedSignal) DeepCopy() *SharedSignal {
	if in == nil {
		return nil
	}
	out := new(SharedSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Signal) DeepCopyInto(out *Signal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Signal.
func (in *Signal) DeepCopy() *Signal {
	if in == nil {
		return nil
	}
	out := new(Signal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPatchStatus) DeepCopyInto(out *WorkloadPatchStatus) {
	*out = *in
	if in.BlockReasons != nil {
		in, out := &in.BlockReasons, &out.BlockReasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPatchStatus.
func (in *WorkloadPatchStatus) DeepCopy() *WorkloadPatchStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadPatchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSpec) DeepCopyInto(out *WorkloadSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.HelmValues != nil {
		in, out := &in.HelmValues, &out.HelmValues
		*out = new(HelmValuesSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Scaling = in.Scaling
	out.Bounds = in.Bounds
	in.Policy.DeepCopyInto(&out.Policy)
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSpec.
func (in *WorkloadSpec) DeepCopy() *WorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadStatus) DeepCopyInto(out *WorkloadStatus) {
	*out = *in
	if in.Patch != nil {
		in, out := &in.Patch, &out.Patch
		*out = new(WorkloadPatchStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Recovery != nil {
		in, out := &in.Recovery, &out.Recovery
		*out = new(RecoveryStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadStatus.
func (in *WorkloadStatus) DeepCopy() *WorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadStatus)
	in.DeepCopyInto(out)
	return out
}
